### ISSUE TITLE
buybot: restrict buying at the same resistance multiple times.

### ISSUE THREAD

**Issue by p0ll3** [svanas/nefertiti#52] opened 2021-11-19 15:47 UTC
In some cases it could be really bad if the bot buys at the same resistance every hour multiple times. If the coins drops after that and the sellorders never fill, you are stuck with "lots of bets on the same situation", which is kinda unnecessary.

An Idea for easy implementation. A new arg that sets n option for the buybot to check the open sellorders whether they have the same price. If so, don't open the order.

**Comment by TaipeiHere** [comment] 2021-11-19 16:27
Which market? What prices did the buy orders fill at?

**Comment by p0ll3** [comment] 2021-11-19 16:54
![Screenshot 2021-11-19 175103](https://user-images.githubusercontent.com/34091527/142660820-fea01d5a-1812-4a90-b570-1e7025f0e04c.png)

Something like that.

**Comment by d00vy** [comment] 2021-11-19 16:59
> ![Screenshot 2021-11-19 175103](https://user-images.githubusercontent.com/34091527/142660820-fea01d5a-1812-4a90-b570-1e7025f0e04c.png)
> 
> Something like that.

Were the original sell orders changed after they were posted by the bot?

**Comment by p0ll3** [comment] 2021-11-19 17:05
OK probably confusing, I only meant these trades. I included the whole graph for the price on the right, my fault.
![image](https://user-images.githubusercontent.com/34091527/142662363-143ca032-4c32-4c87-ad2a-2baaa004db00.png)

The one after the two sells in the rise was done manually, because of Kucoin which didn't sell everything.But every buy order had its sell order. They filled all at the rise.

**Comment by d00vy** [comment] 2021-11-19 17:14
> The one after the two sells in the rise was done manually, because of Kucoin which didn't sell everything.But every buy order had its sell order. They filled all at the rise.

I'm trying to be clear because if you change the sell orders, it seems to break Nefertiti's tracking of unfilled sell orders and it will go back to thinking it's free to buy at the same price. Just trying to make sure that the sell bot posted 6 corresponding sell orders that weren't changed at any time.

**Comment by p0ll3** [comment] 2021-11-19 18:03
I did the sells manually after it already sold every buy order and none open sellorder remained. On Kucoin sometimes it doesn't fill the same amount as it bought. Thats something different.

**Comment by svanas** [comment] 2021-11-21 11:13
I am not convinced we have a bug here. As a matter of fact, I assumed such problem to be [fixed in an earlier commit](https://github.com/svanas/nefertiti/commit/a6cd74180d76b56b0ce665e1f12a9f9c2ad186fe).

I'm afraid the charts - as nice as they are - do to provide us with any reproducible proof. Do you happen to have a screen shot where...
1. you have a (unsold) sell order in your book, and
2. you have a (unfilled) limit buy order in your book, and
3. order (1) got bought at the same price as (2)

Also, it would help knowing if this problem is isolated to Bitstamp, or if you are having it on other exchanges, too.

**Comment by p0ll3** [comment] 2021-11-22 18:48
I don't see it as a bug either, it totally makes sense if the bot does that. But probably it would be good if it could be avoided (less risk). My last screenshots were of Kucoin. Here I have a similar situation of today, these pictures are from GDAX.

![Screenshot 2021-11-22 124947](https://user-images.githubusercontent.com/34091527/142917898-9167b05a-edcc-47af-9ba4-268a005a25d7.png)

Closed Orders:
![Screenshot 2021-11-22 125028](https://user-images.githubusercontent.com/34091527/142917969-dce90760-a3db-4c81-a091-796dee62a894.png)

open orders:
![Screenshot 2021-11-22 125044](https://user-images.githubusercontent.com/34091527/142918038-3e7b6b4a-1d34-4711-8cb7-1dcf10e393be.png)

**Comment by svanas** [comment] 2021-11-22 18:57
> I don't see it as a bug either, it totally makes sense if the bot does that.

The buy bot should never place any buys at prices where a corresponding sell order has not been filled yet. If it is doing that, we do have a bug.

I'm afraid your screen shots do not prove much, as much as I appreciate you taking the time to shoot them. Closed orders don't tell us anything. Looking at your open orders, I see a limit buy at 0.0000180 and a limit sell at 0.00000185. Assuming your --mult is set to 1.05 (aka 5%) then 0.00000185 does not correspond with 0.0000180.

**Comment by p0ll3** [comment] 2021-11-22 19:15
Sorry, i forgot to mention. I'm using a mult set to 3% so 0,0000180 * 1,03 = 0,00001854 whicht fits the open sell orders.

So that I understand correctly, the bot should never buy at the same price hour (with repeat=1). But If its higher/lower it should do it?
Is there something I could log/do to help?

**Comment by svanas** [comment] 2021-11-22 19:21
> Sorry, i forgot to mention. I'm using a mult set to 3% so 0,0000180 * 1,03 = 0,00001854 which fits the open sell orders.

What NEF version are you running?

> So that I understand correctly, the bot should never buy at the same price hour (with repeat=1). But If its higher/lower it should do it?

Correct. It should only ever buy lower.

> Is there something I could log/do to help?

Can you send me your command line (sans your API keys) please? I would love to reproduce and fix this for you.

**Comment by p0ll3** [comment] 2021-11-22 19:32
> Correct. It should only ever buy lower.
Ah nice! 

version 0.0.184

buy:
nef buy --api-key= --api-secret= --telegram-app-key= --telegram-chat-id= --pushover-app-key=NONE --pushover-user-key=NONE --ignore-error --exchange=GDAX --market=SKL-BTC,OGN-BTC,ICP-BTC,ALGO-BTC,LINK-BTC,XTZ-BTC --quote=BTC --price=0.00035 --api-passphrase= --top=1 --repeat=1.0 --strict --notify=2

sell:
nef sell --exchange=GDAX --api-key= --api-secret= --api-passphrase= --pushover-app-key=none --pushover-user-key=none --telegram-app-key= --telegram-chat-id= --ignore-error --mult=1.03 --notify=1 --earn=BTC-EUR,ETH-EUR,BCH-EUR,ADA-EUR,BTC-USDC,ETH-USDC,ADA-BTC,ETH-BTC,BCH-BTC

**Comment by d00vy** [comment] 2021-11-22 21:10
> Closed Orders: ![Screenshot 2021-11-22 125028](https://user-images.githubusercontent.com/34091527/142917969-dce90760-a3db-4c81-a091-796dee62a894.png)
> 
> open orders: ![Screenshot 2021-11-22 125044](https://user-images.githubusercontent.com/34091527/142918038-3e7b6b4a-1d34-4711-8cb7-1dcf10e393be.png)

This does not look right. You can clearly see that there was a sell order open from 06:07, but the bot made 3 more purchases at the same exact price (180).

I wonder: how does it behave if you take out `--strict`? That is the _only_ thing I see in your command line that's different from mine on GDAX, and I have never had this happen.

**Comment by jaro3** [comment] 2021-11-23 05:29
I just add my case from the Telegram, same price buying without selling happened to me twice on the Bitstamp:

sell --exchange=Bitstamp --mult=1.04 --ignore-error

buy --exchange=BITS --market=etheur --quote=EUR --price=170 --repeat=0.2 --top=3 --dip=2 --dist=4 --pip=30 --ignore=error

bought same price 6x in a row while having the unfilled sell orders accumulating...

![Screenshot from 2021-11-22 14-58-33](https://user-images.githubusercontent.com/12386887/142975078-88ef57d0-e3f9-41d2-b811-59bb9ce1fe07.png)
![Screenshot from 2021-11-23 14-19-54](https://user-images.githubusercontent.com/12386887/142975102-40c59c70-8efc-4ee4-ba2a-2c612c1a3f53.png)
![Screenshot from 2021-11-23 14-21-33](https://user-images.githubusercontent.com/12386887/142975338-283d9bee-85e1-4ae6-bf57-37487dc13e39.png)

**Comment by jaro3** [comment] 2021-11-23 05:37
Previous case with the --dca option in place:
![Screenshot from 2021-11-23 14-35-19](https://user-images.githubusercontent.com/12386887/142975922-95cfec92-94b6-48db-bcbd-3242b8824acb.png)

**Comment by jaro3** [comment] 2021-11-23 05:41
The bot should not be re-buying at the same price unless it sells irrespective of the market conditions (e.g. sideway market) or at least have an option for such behavior

> Previous case with the --dca option in place: ![Screenshot from 2021-11-23 14-35-19](https://user-images.githubusercontent.com/12386887/142975922-95cfec92-94b6-48db-bcbd-3242b8824acb.png)

**Comment by svanas** [comment] 2021-11-23 09:17
Wait, I think I see what is happening. This has nothing to do with `--strict`

Both @jaro3 and @p0ll3 deviate from the default `--mult` value. But while they are telling the sell bot, they aren't telling the buy bot. Consequently, the buy bot assumes 1.05 (aka 5%) while in reality, the sell bot is selling at a different multiplier.

Here are our options:
1. Communiate in our medium.com articles that when you deviate from `--mult` you need to do so both in your sell bot and your buy bots if you are running the standard (built-in) strategy, or
2. Somehow share/communicate the `--mult` value, analog to how the bots are syncing the rate limits with each other. I am not a fan of this approach because it introduces local storage and that is something I have tried to avoid so far.

**Closed by svanas** 2021-11-23 09:17 UTC

**Comment by p0ll3** [comment] 2021-11-23 09:45
Ah nice!

Option 1 seems quick/easy: In addition to the medium.com articles, it should be mentioned in the
`nefertiti buy --help` reference.

**Comment by jaro3** [comment] 2021-11-23 10:21
Great, so it works like the buy bot first checks if there isn't any sell order at the --mult value it is using before placing a new order?  Then this should work even in situations when the bot/computer gets restarted or you place some sell orders manually!

**Comment by svanas** [comment] 2021-11-23 10:24
> Great, so it works like the buy bot first checks if there isn't any sell order at the --mult value it is using before placing a new order?

How it actually works; the buy bot searches for (unsold) sell orders, then calculates at what price those (unsold) sell orders got bought at, then exclude this from the pip range where it looks for supports.

> Then this should work even in situations when the bot/computer gets restarted or you place some sell orders manually!

Correct.

**Comment by jaro3** [comment] 2021-11-23 10:28
Is the check to look at the sell orders only at exactly the same --mult value corresponding to the buy order to be placed or at the same or LOWER --mult values?  I mean if there is any standing sell order with price corresponding to the used --mult value for the buy order to be placed or lower price the bot should be inhibited from placing that buy order or place it at lower support level/price.  If it works like this it's perfect:-)

**Comment by jaro3** [comment] 2021-11-23 10:31
> > Great, so it works like the buy bot first checks if there isn't any sell order at the --mult value it is using before placing a new order?
> 
> How it actually works; the buy bot searches for (unsold) sell orders, then calculates at what price those (unsold) sell orders got bought at, then exclude this from the pip range where it looks for supports.
> 
> > Then this should work even in situations when the bot/computer gets restarted or you place some sell orders manually!
> 
> Correct.

I see, thanks for the explanation, clear now.

**Comment by jaro3** [comment] 2021-11-23 10:36
> Ah nice!
> 
> Option 1 seems quick/easy: In addition to the medium.com articles, it should be mentioned in the `nefertiti buy --help` reference.

yes, the --mult option is only shown in --help for the sell bot

**Comment by jaro3** [comment] 2021-11-26 15:02
It is not working, all bots have --mult=1.04 but I still see the buy bot to put a new order at 3500 ETH/EUR while there is already one such order @3500 completed a while ago (with no corresponding sell completed yet). This happened again during today's crushing and the realized multiple buy orders on other pairs such as BTC/EUR are so close to each other!  I am afraid the --dist= option doesn't look at already completed buy orders and only calculates the distance between newly set orders within the --top limit?
