### ISSUE TITLE
KuCoin issue:  NEF SELL bot market sells for a loss

### ISSUE THREAD

**Issue by d00vy** [svanas/nefertiti#57] opened 2021-12-04 17:05 UTC
Nefertiti immediately market sells at a loss. This has happened twice now.

```
:~$ cryptotrader --version
0.0.185
```
Command: `:~$ cryptotrader sell --exchange=KUCN`

<html>
<body>

Filled Time | Pair | Side | Type | Filled Price
-- | -- | -- | -- | -- |
2021/11/26 02:32:26 | HTR/BTC | Sell | Market Order | 0.00002391BTC
2021/11/26 02:32:21 | HTR/BTC | Buy | Limit Order | 0.00002435BTC

</body>
</html>

<html>
<body>

Filled Time | Pair | Side | Type | Filled Price
-- | -- | -- | -- | -- |
2021/12/03 23:22:04 | BSV/USDC | Sell | Market Order | 106.06USDC
2021/12/03 23:22:04 | BSV/USDC | Sell | Market Order | 106.07USDC
2021/12/03 23:21:33 | BSV/USDC | Buy | Limit Order | 110.9USDC

</body>
</html>

**Comment by svanas** [comment] 2021-12-06 17:43
The issue appears to be with KuCoin re-announcing old orders to us that weren't recently filled. We should be able to do something similar for KuCoin as what we did for Binance here: https://github.com/svanas/nefertiti/blob/master/exchanges/binance.go#L424-L429

**Comment by d00vy** [comment] 2021-12-06 17:46
No, responding to old orders is issue #59

This issue was not in response to old orders on the KuCoin API

**Comment by p0ll3** [comment] 2021-12-06 20:38
I have some similar strange trades on KuCoin. The Bot buys and sells at a loss

21 Nov 2021 09:47:40 KUCN: OLT/BTC Limit  Buy  0.0000011500 217.3913 217.3913 0.00024999 Closed
21 Nov 2021 13:04:52 KUCN: OLT/BTC Market Sell 0.0000011457 217.3913 217.3913 0.00024906 Closed

21 Nov 2021 18:59:23 KUCN: OLT/BTC Limit  Buy  0.0000011000 318.1818 318.1818 0.00034999 Closed
21 Nov 2021 21:25:07 KUCN: OLT/BTC Market Sell 0.0000010822 318.1818 318.1818 0.00034433 Closed



Additional wierd stuff like that happend. Looks like Stoploss, but there is none on KuCoin. The coin dropped 13% before that happend.
28 Nov 2021 04:24:57 KUCN: OLT/BTC Market Sell 0.0000007972 437.5000 437.5 0.00034877 Closed
28 Nov 2021 04:56:36 KUCN: OLT/BTC Limit  Buy  0.0000008000 437.5000 437.5 0.00035000 Closed

All those orders happend without a --mult set on the buybot (I had the sellbot set to a mult of 3% and didn't know that I have to set it also on the buybot). Don't know if this could cause problems like that.

**Comment by TaipeiHere** [comment] 2021-12-09 06:40
@d00vy & @svanas suspects root cause may be KuCoin specific where:

**Comment by d00vy** [comment] 2021-12-09 15:57
> This issue was not in response to old orders on the KuCoin API

There were no old orders associated with this

**Comment by svanas** [comment] 2021-12-10 05:49
Fixed in https://github.com/svanas/nefertiti/commit/006a79cc03775456038d5b60bbe849e2645c74a5

**Closed by svanas** 2021-12-10 05:49 UTC
Labels: bug
